version: '3.8'

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
    environment:
      TZ: 'America/Denver'
      WEBPASSWORD: /run/secrets/pihole_password
    secrets:
      - pihole_password
    # Volumes store your data between container upgrades
    volumes:
      - type: volume
        source: pihole-data
        target: /etc/pihole/
      - type: volume
        source: pihole-dnsmasq
        target: /etc/dnsmasq.d/
    networks:
      - traefik-public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.pihole.rule=Host(`pihole.burke-pi.org`)'
        - 'traefik.http.routers.pihole.entrypoints=web'

volumes:
  pihole-data:
  pihole-dnsmasq:

secrets:
  pihole_password:
    external: true

networks:
  traefik-public:
    external: true
