services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3002:3000
    volumes:
      - /scratch/homepage-config:/app/config # Make sure your local config directory exists
    environment:
      PUID: 1000
      PGID: 1000
    networks:
      - traefik-public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.homepage.rule=Host(`homepage.burke-pi.org`)'
        - 'traefik.http.routers.homepage.tls.certresolver=cloudflare'
        - 'traefik.http.routers.homepage.tls=true'
        - 'traefik.http.routers.homepage.entrypoints=websecure'
        - 'traefik.http.services.homepage.loadbalancer.server.port=3002'

networks:
  traefik-public:
    external: true
