
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv-nfs-etc   # < name of the persisant volume ("pv") in kubenetes
  namespace: pihole            # < namespace where place the pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi                   # < max. size we reserve for the pv
  accessModes:
    - ReadWriteMany                # < Multiple pods can write to storage 
  persistentVolumeReclaimPolicy: Retain # < The persistent volume can reclaimed 
  nfs:
    path: /mnt/storage/nfs/pihole/etc       # < Name of your NFS share with subfolder
    server: 192.168.0.11        # < IP number of your NFS server
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv-nfs-dnsmasq   # < name of the persisant volume ("pv") in kubenetes
  namespace: pihole            # < namespace where place the pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi                   # < max. size we reserve for the pv. A bigger value than the configdata
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/storage/nfs/pihole/dnsmasq.d         
    server: 192.168.0.11
    readOnly: false