---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "pihole"
  name: "pihole-etc-pv-claim"
spec:
  storageClassName: "nfs-csi"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "pihole"
  name: "pihole-dnsmasq-pv-claim"
spec:
  storageClassName: "nfs-csi"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"