---

version: '3.8'

services:
  traefik:
    image: traefik:v3.2
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /scratch/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - /scratch/traefik/certs/:/var/traefik/certs/
      - /scratch/traefik/conf/:/etc/traefik/conf/
    networks:
      - traefik-public
    secrets:
      - cloudflare_domain_token
    environment:
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cloudflare_domain_token
      - CF_ZONE_API_TOKEN_FILE=/run/secrets/cloudflare_domain_token
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.burke-pi.org`)"
        - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
        - "traefik.http.routers.traefik.tls=true"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        #- "traefik.http.routers.traefik.middlewares=authentik@file"

configs:
  traefik-config:
    external: true

secrets:
  cloudflare_domain_token:
    external: true

networks:
  traefik-public:
    external: true

volumes:
  traefik-data:
