---

version: '3.8'

services:
  traefik:
    image: traefik:v3.2
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: traefik-data
        target: /var/traefik/certs/
    networks:
      - traefik-public
    configs:
      - source: traefik-config
        target: /etc/traefik/traefik.yaml
        mode: 0444
    secrets:
      - cloudflare_domain_token
    environment:
      - CF_DNS_API_TOKEN=/run/secrets/cloudflare_domain_token
      - CF_ZONE_API_TOKEN=/run/secrets/cloudflare_domain_token
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

configs:
  traefik-config:
    external: true

secrets:
  cloudflare_domain_token:
    external: true

networks:
  traefik-public:
    external: true

volumes:
  traefik-data:
