homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 39.756286256208796
  longitude: -104.89106311203972
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 1600
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Denver

# authentication
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
        - 192.168.0.11
        - 192.168.0.12
        - 127.0.0.1
        - 10.1.75.0

default_config:

http:
  ip_ban_enabled: false
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.1.0.0/16
    - 192.168.0.0/24
    - 10.1.75.0/24