apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: lan-network
  namespace: home-assistant
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "lan-network",
    "type": "macvlan",
    "mode": "bridge",
    "master": "eth0",
    "ipam": {
      "type": "host-local",
      "subnet": "192.168.0.0/24",
      "rangeStart": "192.168.0.240",
      "rangeEnd": "192.168.0.241",
      "routes": [
        { "dst": "0.0.0.0/0" }
      ],
      "gateway": "192.168.0.1"
    }
  }'