apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassist-pv-claim
  namespace: home-assistant
  labels:
    app: homeassist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: "nfs-csi"