global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: INFO
providers:
  docker:
    exposedByDefault: false
    api:
      insecure: true
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
