---
- name: Update all Raspberry Pis
  hosts: all
  become: true
  tasks:
    - name: Update the package list
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes

    - name: Check if a reboot is required
      register: reboot_required
      stat:
        path: /var/run/reboot-required

    - name: Reboot the system if required
      reboot:
      when: reboot_required.stat.exists

