---
- hosts: nfs_servers
  become: yes
  tasks:
    - name: Create a new partition on the SSD
      command: 
        cmd: "{{ item }}"
      with_items:
        - parted -s /dev/sda mklabel gpt
        - parted --a optimal /dev/sda mkpart primary ext4 0% 100%
        - mkfs -t ext4 /dev/sda1

    - name: Create a new directory and mount the SSD
      block:
        - file:
            path: /mnt/storage
            state: directory
            owner: "{{ ansible_user }}"
            recurse: yes
        - mount:
            path: /mnt/storage
            src: /dev/sda1
            fstype: ext4
            opts: defaults,user
            state: mounted

    - name: Install NFS Server
      apt:
        name: nfs-kernel-server
        state: present
    
    - name: Create a mount point for the NFS share
      block:
        - file:
            path: /mnt/storage/nfs
            state: directory

    - name: Change owner of /nfs to nobody:nogroup
      file:
        path: /mnt/storage/nfs
        owner: nobody
        group: nogroup

    - name: Change permissions of /mnt/storage/nfs to 0777
      file:
        path: /mnt/storage/nfs
        mode: '0777'

    - name: Change RPCMOUNTDOPTS in /etc/default/nfs-kernel-server
      lineinfile:
        path: /etc/default/nfs-kernel-server
        regexp: '^RPCMOUNTDOPTS='
        line: 'RPCMOUNTDOPTS=""'
        state: present

    - name: Add the NFS share to /etc/exports
      lineinfile:
        path: /etc/exports
        line: '/mnt/storage/nfs 192.168.0.0/24(rw,sync,no_subtree_check)'

    - name: Run exportfs -ra
      command: sudo exportfs -ra

    - name: Restart the NFS server
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      with_items:
        - rpcbind.service
        - nfs-server.service
...