---
- hosts: all
  become: yes
  tasks:
    - name: Update Raspberry Pi OS
      apt:
        update_cache: yes
        upgrade: dist

    - name: Add configuration to cmdline.txt
      lineinfile:
        path: /boot/firmware/cmdline.txt
        backrefs: yes
        regexp: '^(.*)$'
        line: '\1 cgroup_enable=memory cgroup_memory=1'

    - name: Install tools
      apt:
        name:
          - vim
          - git
          - curl
          - wget
          - ffmpeg
        state: present

    - name: Add PoE fan control to config.txt
      blockinfile:
        path: /boot/config.txt
        block: |
          # PoE Hat Fan Speeds
          dtparam=poe_fan_temp0=50000
          dtparam=poe_fan_temp1=60000
          dtparam=poe_fan_temp2=70000
          dtparam=poe_fan_temp3=80000

    - name: Reboot the server
      reboot:
...