---

services:
  jellyfin:
    image: jellyfin/jellyfin
    user: 1000:1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - jellyfin-config:/config
      - jellyfin-media:/media
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.rpi-model == 4
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.burke-pi.org`)"
        - "traefik.http.routers.jellyfin.tls.certresolver=cloudflare"
        - "traefik.http.routers.jellyfin.tls=true"
        - "traefik.http.routers.jellyfin.entrypoints=websecure"
        - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    networks:
        - traefik-public
    ports:
      - 8096:8096

volumes:
  jellyfin-media:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.50.5,nfsvers=4"
      device: ":/picluster-jellyfin/media"
  jellyfin-config:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.50.5,nfsvers=4"
      device: ":/picluster-jellyfin/config"

networks:
  traefik-public:
    external: true

