---
- hosts: k8_cluster
  become: true

  tasks:
    - name: Stop microk8s
      shell: /snap/bin/microk8s stop
      ignore_errors: yes

    - name: Shutdown node
      shell: shutdown now
      ignore_errors: yes
...
